# Generated by Django 4.2.2 on 2023-07-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_board_goalcategory_board_boardparticipant'),
    ]

    operations = [
    ]
